Repository e-library-on-containers/e-library-on-containers, pull requests merged in 2022-11, with the labels that each got.

#2 #1 Add solution with validation library
  .github/actions/set-env/action.yml
  .github/vars/shared-variables.env
  .github/workflows/functional-validation-publish.yml
  .github/workflows/functional-validation-test.yml
  src/eLibraryOnContainers.sln
  src/shared/FunctionalValidation.Tests/FakeTests.cs
  src/shared/FunctionalValidation.Tests/FunctionalValidation.Tests.csproj
  src/shared/FunctionalValidation/FunctionalValidation.csproj
  src/shared/FunctionalValidation/IValidator.cs
Labels: enhancement

#4 #3 Add DocFX and C4-Builder docs
  .github/workflows/publish-docs.yml
  c4builder/.c4builder
  c4builder/src/1 System Context Diagram/system-context-diagram.md
  c4builder/src/1 System Context Diagram/system-context-diagram.puml
  c4builder/src/2 Container Diagram/container.md
  c4builder/src/3 Component Diagrams/1 API Gateway/api-gateway.md
  c4builder/src/3 Component Diagrams/2 Identity service/identity-service.md
  docs/.gitignore
  docs/api/.gitignore
  docs/api/index.md
  docs/articles/diagrams.md
  docs/articles/toc.yml
  docs/docfx.json
  docs/index.md
  docs/toc.yml
Labels: documentation, enhancement

#8 #7 Add scripts for dockerized local C4-Builder development
  scripts/c4dev/Dockerfile
  scripts/c4dev/build-image.sh
  scripts/c4dev/recreate-dev.sh
  scripts/c4dev/rm-dev.sh
  scripts/c4dev/run-dev.sh
Labels: enhancement

#10 #9 Add Container diagram
  c4builder/src/2 Container Diagram/container.md
  c4builder/src/2 Container Diagram/container.puml
Labels: documentation

#12 #11 Fix docs deployment
  .github/workflows/build-docs.yml
  .github/workflows/publish-docs.yml
Labels: bug

#17 #16 Implement Functional Validation
  src/shared/FunctionalValidation.Tests/AbstractValidatorTests.cs
  src/shared/FunctionalValidation.Tests/Extension/ApplicationErrorExtensionsTests.cs
  src/shared/FunctionalValidation.Tests/Extension/FunctionalValidationExtensionsTests.cs
  src/shared/FunctionalValidation.Tests/Extension/ResultErrorExtensionsTests.cs
  src/shared/FunctionalValidation.Tests/FakeTests.cs
  src/shared/FunctionalValidation.Tests/FunctionalValidatorTests.cs
  src/shared/FunctionalValidation.Tests/ImplementedValidators/LongerThan5CharactersValidator.cs
  src/shared/FunctionalValidation.Tests/ImplementedValidators/NotNullOrWhitespaceValidator.cs
  src/shared/FunctionalValidation.Tests/New.cs
  src/shared/FunctionalValidation/AbstractValidator.cs
  src/shared/FunctionalValidation/Errors/ApplicationError.cs
  src/shared/FunctionalValidation/Errors/ErrorType.cs
  src/shared/FunctionalValidation/Errors/NotFoundError.cs
  src/shared/FunctionalValidation/Errors/RestrictedAccessError.cs
  src/shared/FunctionalValidation/Errors/UnknownError.cs
  src/shared/FunctionalValidation/Errors/ValidationError.cs
  src/shared/FunctionalValidation/Extensions/ApplicationErrorExtensions.cs
  src/shared/FunctionalValidation/Extensions/FunctionalValidationExtensions.cs
  src/shared/FunctionalValidation/Extensions/ResultErrorExtensions.cs
  src/shared/FunctionalValidation/FunctionalValidation.csproj
  src/shared/FunctionalValidation/FunctionalValidator.cs
  src/shared/FunctionalValidation/IFunctionalValidator.cs
  src/shared/FunctionalValidation/IValidator.cs
Labels: enhancement

#18 #14 Add Component diagram for Identity service
  c4builder/.gitignore
  c4builder/src/3 Component Diagrams/2 Identity service/identity-service.md
  c4builder/src/3 Component Diagrams/2 Identity service/identity-service.puml
Labels: documentation

#24 #5 Add Component diagram for Rental service
  c4builder/src/2 Container Diagram/container.puml
  c4builder/src/3 Component Diagrams/3 Rentals service/rentals-service.md
  c4builder/src/3 Component Diagrams/3 Rentals service/rentals-service.puml
Labels: documentation

#25 #5 Fix typo in Rental Component Diagram
  c4builder/src/3 Component Diagrams/3 Rentals service/rentals-service.md
Labels: documentation

#27 #22 Add template for NuGet config file
  .gitignore
  src/nuget.template.config
Labels: enhancement

#28 #23 Add project repository details
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement
