Repository e-library-on-containers/e-library-on-containers, pull requests merged in 2023-01, with the labels that each got.

#33 #32 Add local identity dev environment
  .dev-env
  .github/workflows/identity-api-publish-docker.yml
  .github/workflows/identity-db-updater-publish-docker.yml
  dev-compose.ps1
  dev-compose.sh
  dev-compose.sh.save
  docker-compose.dev.yml
  docker-compose.yml
  src/identity/Identity.Api.Dockerfile
  src/identity/Identity.Database.Dockerfile
  src/identity/api/Identity.Api/Infrastructure/PipelineConfiguration.cs
Labels: enhancement

#29 #6 Add component diagram for books service
  .gitignore
  c4builder/src/3 Component Diagrams/4 Books service/books-service.md
  c4builder/src/3 Component Diagrams/4 Books service/books-service.puml
Labels: documentation

#68 #67 Fix apiUrl for local setup
  src/front/src/environments/environment.ts
Labels: bug
